### ISSUE TITLE
Openapi Endpoint Broken

### ISSUE THREAD

**Issue by ainsleyclark** [janbuchar/payload-oapi#4]
Hi there,

I'm just wondering how to access this spec? When navigating to `/openapi.json` on localhost I get a 404?

```
openapi({
	openapiVersion: '3.1',
	specEndpoint: '/openapi.json',
	metadata: {
		title: 'Dev API',
		version: '0.0.1' ,
	}
}),
```

**Comment by janbuchar** [comment]
Hi, which version of payload are you on?

**Comment by ainsleyclark** [comment]
Hi @janbuchar 

Version 2.0

**Comment by janbuchar** [comment]
Understood. I will see if there are any updates needed for 2.0 and get back to you.

**Comment by janbuchar** [comment]
@ainsleyclark I just published version 0.1.0, can you check if it works?

**Comment by ainsleyclark** [comment]
Thanks @janbuchar 

I have another error `Error: Unknown reference: FAQs` but I think that's something to do with my config, it was `404`ing before.

**Comment by janbuchar** [comment]
@ainsleyclark sounds like it. I'm closing the issue, if you find out that this is in fact a problem with the plugin, feel free to reopen this. In that case, please provide a minimal reproducible example of the problem so that I can troubleshoot it better.
